'use strict';

module.exports = {
    GET_USERS: 'GET_USERS',
    USERS_LIST: 'USERS_LIST',
    GET_MESSAGES: 'GET_MESSAGES',
    SEND_MESSAGE: 'SEND_MESSAGE',
    NEW_MESSAGE: 'NEW_MESSAGE',
    DELETE_MESSAGES: 'DELETE_MESSAGES'
};
